controller: constellation\mynest\Heat\Controller\Pi
cache: cache
point:
  lat: 43.43
  lon: -90.80
noaa_apikey: "my_pi_controller al@constellationwebservices.com"
zones:
  -
    zone: 1
    source: { startup: 1, cycle: 60, rise: 60, offset: 180 }
    schedule: { all: { 8: 65, 22: 60 } }
sources:
  woodstove: {all: {8: 15, 22: 15, 0: 15, 2: 15}} 
  sun: {all: {10: 10, 14: 0}}
