controller: constellation\mynest\Heat\Controller\Pi
cache: cache
point:
  lat: 43.43
  lon: -90.80
zones:
  -
    zone: 1
    source: { startup: 5, cycle: 60, rise: 70, offset: 180 }
    schedule: { all: { 8: 65, 22: 60 } }
sources:
  woodstove: {all: {8: 35, 22: 30, 0: 20, 2: 10}} 
  sun: {all: {10: 10, 14: 0}}
